name: mounarchtech_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.3.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
